name; Build Frontend

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -name build frontend using bun
      run: |
        cd frontend
        bun install
        bun run build

